//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: login.proto
package com.ck567.netty.chatroom.message.entity
@kotlin.jvm.JvmSynthetic
inline fun loginResp(block: LoginRespKt.Dsl.() -> Unit): LoginProto.LoginResp =
  LoginRespKt.Dsl._create(LoginProto.LoginResp.newBuilder()).apply { block() }._build()
object LoginRespKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: LoginProto.LoginResp.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: LoginProto.LoginResp.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): LoginProto.LoginResp = _builder.build()

    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>string code = 1;</code>
     */
    var code: kotlin.String
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>string code = 1;</code>
     */
    fun clearCode() {
      _builder.clearCode()
    }

    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun LoginProto.LoginResp.copy(block: LoginRespKt.Dsl.() -> Unit): LoginProto.LoginResp =
  LoginRespKt.Dsl._create(this.toBuilder()).apply { block() }._build()
