//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: login.proto
package com.ck567.netty.chatroom.message.entity
@kotlin.jvm.JvmSynthetic
inline fun loginReq(block: LoginReqKt.Dsl.() -> Unit): LoginProto.LoginReq =
  LoginReqKt.Dsl._create(LoginProto.LoginReq.newBuilder()).apply { block() }._build()
object LoginReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: LoginProto.LoginReq.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: LoginProto.LoginReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): LoginProto.LoginReq = _builder.build()

    /**
     * <code>string user_name = 1;</code>
     */
    var userName: kotlin.String
      @JvmName("getUserName")
      get() = _builder.getUserName()
      @JvmName("setUserName")
      set(value) {
        _builder.setUserName(value)
      }
    /**
     * <code>string user_name = 1;</code>
     */
    fun clearUserName() {
      _builder.clearUserName()
    }

    /**
     * <code>string password = 2;</code>
     */
    var password: kotlin.String
      @JvmName("getPassword")
      get() = _builder.getPassword()
      @JvmName("setPassword")
      set(value) {
        _builder.setPassword(value)
      }
    /**
     * <code>string password = 2;</code>
     */
    fun clearPassword() {
      _builder.clearPassword()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun LoginProto.LoginReq.copy(block: LoginReqKt.Dsl.() -> Unit): LoginProto.LoginReq =
  LoginReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()
